"""
Chapter 4 Examples
==================

"""

from predicate_lambda_calculus import *


def RunExamples():
  print('Examples from 5.1')
  nat = TypeVar('nat', Star())
  n = Var('n', nat)
  S = TypeExpression(TypeVar('S', PiKind(n, Star())))
  print('Indexed sets:', S)
  print(TypeExpression(TAbstract(n, TApply(S, n))))
  V = TypeExpression(TypeVar('V', PiKind(n, Star())))
  print('Vectors of length n:', V)
  Vt = TypeExpression(TAbstract(n, TApply(V, n)))
  print(Vt)
  P = TypeExpression(TypeVar('P', PiKind(n, Star())))
  print('Proposition for each number n:', P)
  Pt = TypeExpression(TAbstract(n, TApply(P, n)))
  print(Pt)
  three = Var('3', nat)
  print(TypeExpression(TApply(Vt, three)))
  print(TypeExpression(TApply(Pt, three)))


  print('\nExamples from 5.2')
  print('Sort rule:')
  sr = SortRule()
  print(sr)
  print('Var rule for type:')
  alpha = TypeVar('α', Star())
  vt = VarRule(alpha, sr.Conclusion())
  vtc = vt.Conclusion()
  print(vt)
  print('Var rule for term:')
  x = Var('x', alpha)
  vr = VarRule(x, vtc)
  vrc = vr.Conclusion()
  print(vr)
  print('Weak rule for type:')
  beta = TypeVar('β', Star())
  print(
      WeakRule(
          beta, vtc, Judgement(vtc.ctx, Statement(KindExpression(Star())))
      )
  )
  print('Weak rule for term:')
  wr = WeakRule(x, vtc, vtc)
  print(wr)
  print('Form rule for kind:')
  print(FormRule(x, vtc, wr.Conclusion()))
  print('Form rule for type:')
  print(FormRule(x, vtc, wr.Conclusion()))
  print('Appl rule for type:')
  F = TypeVar('F', KindExpression(PiKind(x, Star())))
  p_m = Judgement(Context(alpha, x, F), Statement(TypeExpression(F)))
  p_n = Judgement(Context(alpha, x, F), Statement(Expression(x)))
  appl_t = ApplRule(p_m, p_n)
  print(appl_t)
  print('Appl rule for term:')
  f = Var('f', TypeExpression(PiType(x, alpha)))
  p_m = Judgement(Context(alpha, x, f), Statement(Expression(f)))
  p_n = Judgement(Context(alpha, x, f), Statement(Expression(x)))
  appl = ApplRule(p_m, p_n)
  print(appl)
  print('Abst rule for type:')
  p_kind = Judgement(
      Context(alpha, F), Statement(KindExpression(PiKind(x, Star())))
  )
  abst_t = AbstRule(x, appl_t.Conclusion(), p_kind)
  print(abst_t)
  print('Abst rule for term:')
  p_typ = Judgement(
      Context(alpha, f), Statement(TypeExpression(PiType(x, alpha)))
  )
  abst = AbstRule(x, appl.Conclusion(), p_typ)
  print(abst)
  print('Conv rule for kind:')
  S = TypeVar('S', Star())
  x = Var('x', S)
  P = TypeVar('P', PiKind(x, Star()))
  u = Var('u', S)
  y = Var('y', TypeExpression(TApply(TAbstract(x, TApply(P, x)), u)))
  Z = TypeVar('Z', KindExpression(PiKind(y, Star())))
  p_a = Judgement(Context(S, P, u, Z), Statement(TypeExpression(Z)))
  v = Var('v', TypeExpression(TApply(P, u)))
  p_b = Judgement(
      Context(S, P, u, Z), Statement(KindExpression(PiKind(v, Star())))
  )
  print(ConvRule(p_a, p_b))
  print('Conv rule for type:')
  z = Var('z', TypeExpression(TApply(TAbstract(x, TApply(P, x)), u)))
  p_a = Judgement(Context(S, P, u, z), Statement(Expression(z)))
  p_b = Judgement(Context(S, P, u, z), Statement(TypeExpression(TApply(P, u))))
  print(ConvRule(p_a, p_b))


  print('\nExample from 5.3')
  A = TypeVar('A', Star())
  x = Var('x', A)
  P = TypeVar('P', PiKind(x, Star()))
  y = Var('y', TypeExpression(TApply(P, x)))
  d = Derivation()
  p1 = d.SortRule()
  p2 = d.VarRule(A, p1)
  p3 = d.WeakRule(A, p1, p1)
  p4 = d.WeakRule(x, p3, p2)
  p5 = d.FormRule(x, p2, p4)
  p6 = d.VarRule(P, p5)
  p7 = d.WeakRule(P, p2, p5)
  p8 = d.WeakRule(P, p3, p5)
  p9 = d.VarRule(x, p7)
  p10 = d.WeakRule(x, p6, p7)
  p11 = d.ApplRule(p10, p9)
  p12 = d.FormRule(x, p7, p11)
  p13 = d.WeakRule(y, p11, p11)
  p14 = d.FormRule(y, p11, p13)
  p15 = d.FormRule(x, p7, p14)
  p17 = d.VarRule(y, p11)
  p18 = d.AbstRule(y, p17, p14)
  p19 = d.AbstRule(x, p18, p15)
  print(d.FlagFormat())
  print('Shortened version:')
  print(d.ShortenedFlagFormat())


  print('\nExamples from 5.4')
  print('=>-elim:')
  A = TypeVar('A', Star())
  x = Var('x', A)
  B = TypeVar('B', Star())
  M = Var('M', PiType(x, B))
  N = Var('N', A)
  p1 = Judgement(Context(A, B, M, N), Statement(Expression(M)))
  p2 = Judgement(Context(A, B, M, N), Statement(Expression(N)))
  print(ApplRule(p1, p2))
  print('=>-intro:')
  M = Var('M', B)
  p1 = Judgement(Context(A, B, M, x), Statement(Expression(M)))
  p2 = Judgement(Context(A, B, M), Statement(TypeExpression(PiType(x, B))))
  print(AbstRule(x, p1, p2))
  print('∀-elim:')
  S = TypeVar('S', Star())
  x = Var('x', S)
  P = TypeVar('P', PiKind(x, Star()))
  N = Var('N', S)
  p1 = Judgement(Context(S, P, N), Statement(TypeExpression(P)))
  p2 = Judgement(Context(S, P, N), Statement(Expression(N)))
  print(ApplRule(p1, p2))
  print('∀-intro:')
  q = Var('?', TApply(P, x))
  p1 = Judgement(Context(S, P, x), Statement(Expression(q)))
  p2 = Judgement(
      Context(S, P), Statement(TypeExpression(PiType(x, TApply(P, x))))
  )
  print(AbstRule(x, p1, p2))


  print('\nExample from 5.4')
  print('Prove ∀x,y ∈ S: Q(x, y) => ∀u ∈ S: Q(u, u)')
  print('Find inhabitant of type ((Πx:S,y:S.(Q x y)) -> (Πu:S.(Q u u)))')
  S = TypeVar('S', Star())
  x = Var('x', S)
  y = Var('y', S)
  Q = TypeVar('Q', PiKind(x, PiKind(y, Star())))
  u = Var('u', S)
  z_t = TypeExpression(PiType(x, PiType(y, TApply(TApply(Q, x), y))))
  z = Var('z', z_t)
  inhab = Expression(Apply(Apply(z, u), u))
  inhab = Expression(Abstract(z, Abstract(u, Apply(Apply(z, u), u))))
  d = DeriveTerm(Judgement(Context(), Statement(inhab)))
  print(d.ShortenedFlagFormat())


if __name__ == '__main__':
  RunExamples()
