"""
Chapter 4 Examples
==================

"""

from predicate_lambda_calculus import *


def RunExamples():
  print('Examples from 5.1')
  nat = TypeVar('nat', Star())
  n = Var('n', nat)
  S = TypeExpression(TypeVar('S', PiKind(n, Star())))
  print('Indexed sets:', S)
  print(TypeExpression(TAbstract(n, TApply(S, n))))
  V = TypeExpression(TypeVar('V', PiKind(n, Star())))
  print('Vectors of length n:', V)
  Vt = TypeExpression(TAbstract(n, TApply(V, n)))
  print(Vt)
  P = TypeExpression(TypeVar('P', PiKind(n, Star())))
  print('Proposition for each number n:', P)
  Pt = TypeExpression(TAbstract(n, TApply(P, n)))
  print(Pt)
  three = Var('3', nat)
  print(TypeExpression(TApply(Vt, three)))
  print(TypeExpression(TApply(Pt, three)))


  print('\nExamples from 5.2')
  print('Sort rule:')
  sr = SortRule()
  print(sr)
  print('Var rule for type:')
  alpha = TypeVar('α', Star())
  vt = VarRule(alpha, sr.Conclusion())
  vtc = vt.Conclusion()
  print(vt)
  print('Var rule for term:')
  x = Var('x', alpha)
  vr = VarRule(x, vtc)
  vrc = vr.Conclusion()
  print(vr)
  print('Weak rule for type:')
  beta = TypeVar('β', Star())
  print(
      WeakRule(
          beta, vtc, Judgement(vtc.ctx, Statement(KindExpression(Star())))
      )
  )
  print('Weak rule for term:')
  wr = WeakRule(x, vtc, vtc)
  print(wr)
  print('Form rule for kind:')
  print(FormRule(x, vtc, wr.Conclusion()))
  print('Form rule for type:')
  print(FormRule(x, vtc, wr.Conclusion()))
  print('Appl rule for type:')
  F = TypeVar('F', KindExpression(PiKind(x, Star())))
  p_m = Judgement(Context(alpha, x, F), Statement(TypeExpression(F)))
  p_n = Judgement(Context(alpha, x, F), Statement(Expression(x)))
  appl_t = ApplRule(p_m, p_n)
  print(appl_t)
  print('Appl rule for term:')
  f = Var('f', TypeExpression(PiType(x, alpha)))
  p_m = Judgement(Context(alpha, x, f), Statement(Expression(f)))
  p_n = Judgement(Context(alpha, x, f), Statement(Expression(x)))
  appl = ApplRule(p_m, p_n)
  print(appl)
  print('Abst rule for type:')
  p_kind = Judgement(
      Context(alpha, F), Statement(KindExpression(PiKind(x, Star())))
  )
  abst_t = AbstRule(x, appl_t.Conclusion(), p_kind)
  print(abst_t)
  print('Abst rule for term:')
  p_typ = Judgement(
      Context(alpha, f), Statement(TypeExpression(PiType(x, alpha)))
  )
  abst = AbstRule(x, appl.Conclusion(), p_typ)
  print(abst)
  print('Conv rule for kind:')
  S = TypeVar('S', Star())
  x = Var('x', S)
  P = TypeVar('P', PiKind(x, Star()))
  u = Var('u', S)
  y = Var('y', TypeExpression(TApply(TAbstract(x, TApply(P, x)), u)))
  Z = TypeVar('Z', KindExpression(PiKind(y, Star())))
  p_a = Judgement(Context(S, P, u, Z), Statement(TypeExpression(Z)))
  v = Var('v', TypeExpression(TApply(P, u)))
  p_b = Judgement(
      Context(S, P, u, Z), Statement(KindExpression(PiKind(v, Star())))
  )
  print(ConvRule(p_a, p_b))
  print('Conv rule for type:')
  z = Var('z', TypeExpression(TApply(TAbstract(x, TApply(P, x)), u)))
  p_a = Judgement(Context(S, P, u, z), Statement(Expression(z)))
  p_b = Judgement(Context(S, P, u, z), Statement(TypeExpression(TApply(P, u))))
  print(ConvRule(p_a, p_b))


  print('\nExamples from 5.3')
  A = TypeVar('A', Star())
  x = Var('x', A)
  P = TypeVar('P', PiKind(x, Star()))
  y = Var('y', TypeExpression(TApply(P, x)))
  d = Derivation()
  one = d.SortRule()
  two = d.VarRule(A, one)
  three = d.WeakRule(A, one, one)
  four = d.WeakRule(x, three, two)
  five = d.FormRule(x, two, four)
  six = d.VarRule(P, five)
  seven = d.WeakRule(P, two, five)
  eight = d.WeakRule(P, three, five)
  nine = d.VarRule(x, seven)
  ten = d.WeakRule(x, six, seven)
  eleven = d.ApplRule(ten, nine)
  twelve = d.FormRule(x, seven, eleven)
  thirteen = d.WeakRule(y, eleven, eleven)
  fourteen = d.FormRule(y, eleven, thirteen)
  fifteen = d.FormRule(x, seven, fourteen)
  sixteen = d.VarRule(y, eleven)
  seventeen = d.AbstRule(y, sixteen, fourteen)
  eighteen = d.AbstRule(x, seventeen, fifteen)
  print(d.FlagFormat())
  print('Shortened version:')
  print(d.FlagFormat(shorten=True))


if __name__ == '__main__':
  RunExamples()
