"""
Chapter 4 Examples
==================

"""

from predicate_lambda_calculus import *


def RunExamples():
  print('Examples from 5.1')
  nat = TypeVar('nat', Star())
  n = Var('n', nat)
  S = TypeExpression(TypeVar('S', PiKind(n, Star())))
  print('Indexed sets:', S)
  print(TypeExpression(TAbstract(n, TApply(S, n))))
  V = TypeExpression(TypeVar('V', PiKind(n, Star())))
  print('Vectors of length n:', V)
  Vt = TypeExpression(TAbstract(n, TApply(V, n)))
  print(Vt)
  P = TypeExpression(TypeVar('P', PiKind(n, Star())))
  print('Proposition for each number n:', P)
  Pt = TypeExpression(TAbstract(n, TApply(P, n)))
  print(Pt)
  three = Var('3', nat)
  print(TypeExpression(TApply(Vt, three)))
  print(TypeExpression(TApply(Pt, three)))


  print('\nExamples from 5.2')
  print('Sort rule:')
  sr = SortRule(Context())
  print(sr)
  print('Var rule for type:')
  alpha = TypeVar('α', Star())
  vt = VarRule(alpha, sr.Conclusion())
  vtc = vt.Conclusion()
  print(vt)
  print('Var rule for term:')
  x = Var('x', alpha)
  vr = VarRule(x, vtc)
  vrc = vr.Conclusion()
  print(vr)
  print('Weak rule for type:')
  beta = TypeVar('β', Star())
  print(WeakRule(beta, vtc, SortRule(vtc.ctx).Conclusion()))
  print('Weak rule for term:')
  wr = WeakRule(x, vtc, vtc)
  print(wr)
  print('Form rule for kind:')
  print(FormRule(x, vtc, wr.Conclusion()))
  print('Form rule for type:')
  print(FormRule(x, vtc, wr.Conclusion()))
  print('Appl rule for type:')
  F = TypeVar('F', KindExpression(PiKind(x, Star())))
  src = SortRule(Context()).Conclusion()
  vtc = VarRule(alpha, src).Conclusion()
  wtc = WeakRule(x, vtc, vtc).Conclusion()
  vrc = VarRule(x, vtc).Conclusion()
  ftc = FormRule(x, wtc, SortRule(wtc.ctx).Conclusion()).Conclusion()
  vfc = VarRule(F, ftc).Conclusion()
  print(ApplRule(vfc, vrc))
  print('Appl rule for term:')
  f = Var('f', TypeExpression(PiType(x, alpha)))
  src = SortRule(Context()).Conclusion()
  vtc = VarRule(alpha, src).Conclusion()
  wtc = WeakRule(x, vtc, vtc).Conclusion()
  vrc = VarRule(x, vtc).Conclusion()
  ftc = FormRule(x, wtc, wtc).Conclusion()
  vfc = VarRule(f, ftc).Conclusion()
  print(ApplRule(vfc, vrc))
  print('Abst rule for type:')
  src = SortRule(Context()).Conclusion()
  vtc = VarRule(alpha, src).Conclusion()
  wtc = WeakRule(x, vtc, vtc).Conclusion()
  vrc = VarRule(x, vtc).Conclusion()
  ftc = FormRule(x, wtc, SortRule(wtc.ctx).Conclusion()).Conclusion()
  vfc = VarRule(F, ftc).Conclusion()
  ac = ApplRule(vfc, vrc).Conclusion()
  print(AbstRule(x, ac, ftc))
  print('Abst rule for term:')
  src = SortRule(Context()).Conclusion()
  vtc = VarRule(alpha, src).Conclusion()
  wtc = WeakRule(x, vtc, vtc).Conclusion()
  vrc = VarRule(x, vtc).Conclusion()
  ftc = FormRule(x, wtc, wtc).Conclusion()
  vfc = VarRule(f, ftc).Conclusion()
  ac = ApplRule(vfc, vrc).Conclusion()
  print(AbstRule(x, ac, ftc))
  print('Conv rule for kind:')
  S = TypeVar('S', Star())
  x = Var('x', S)
  P = TypeVar('P', PiKind(x, Star()))
  src = SortRule(Context()).Conclusion()
  vsc = VarRule(S, src).Conclusion()
  vxc = VarRule(x, vsc).Conclusion()
  fpc = FormRule(x, vsc, SortRule(vxc.ctx).Conclusion()).Conclusion()
  vpc = VarRule(P, fpc).Conclusion()
  wxc = WeakRule(x, vpc, vsc).Conclusion()
  vxc = VarRule(x, vsc).Conclusion()
  apxc = ApplRule(wxc, vxc).Conclusion()
  axc = AbstRule(x, apxc, fpc).Conclusion()
  u = Var('u', S)
  vuc = VarRule(u, vsc).Conclusion()
  wuc = WeakRule(u, axc, vsc).Conclusion()
  apuc = ApplRule(wuc, vuc).Conclusion()
  z = Var('z', apuc.stmt.subj)
  wzc = WeakRule(z, apuc, apuc).Conclusion()
  fkc = FormRule(z, apuc, SortRule(wzc.ctx).Conclusion()).Conclusion()
  Z = TypeVar('Z', fkc.stmt.subj)
  vzc = VarRule(Z, fkc).Conclusion()
  vuc = VarRule(u, vsc).Conclusion()
  fpc = FormRule(x, vsc, SortRule(vxc.ctx).Conclusion()).Conclusion()
  vpc = VarRule(P, fpc).Conclusion()
  wuc = WeakRule(u, vpc, vsc).Conclusion()
  apuc = ApplRule(wuc, vuc).Conclusion()
  v = Var('v', apuc.stmt.subj)
  wvc = WeakRule(v, apuc, apuc).Conclusion()
  fc = FormRule(v, apuc, SortRule(wvc.ctx).Conclusion()).Conclusion()
  print(ConvRule(vzc, fc))
  print('Conv rule for type:')
  S = TypeVar('S', Star())
  x = Var('x', S)
  P = TypeVar('P', PiKind(x, Star()))
  src = SortRule(Context()).Conclusion()
  vsc = VarRule(S, src).Conclusion()
  vxc = VarRule(x, vsc).Conclusion()
  fpc = FormRule(x, vsc, SortRule(vxc.ctx).Conclusion()).Conclusion()
  vpc = VarRule(P, fpc).Conclusion()
  wxc = WeakRule(x, vpc, vsc).Conclusion()
  vxc = VarRule(x, vsc).Conclusion()
  apxc = ApplRule(wxc, vxc).Conclusion()
  axc = AbstRule(x, apxc, fpc).Conclusion()
  u = Var('u', S)
  vuc = VarRule(u, vsc).Conclusion()
  wuc = WeakRule(u, axc, vsc).Conclusion()
  apuc = ApplRule(wuc, vuc).Conclusion()
  z = Var('z', apuc.stmt.subj)
  vzc = VarRule(z, apuc).Conclusion()
  vuc = VarRule(u, vsc).Conclusion()
  wxc = WeakRule(x, vuc, vsc).Conclusion()
  fpc = FormRule(x, vsc, SortRule(wxc.ctx).Conclusion()).Conclusion()
  vpc = VarRule(P, fpc).Conclusion()
  apuc = ApplRule(vpc, vuc).Conclusion()
  print(ConvRule(vzc, apuc))


if __name__ == '__main__':
  RunExamples()
